# Generated by Django 5.2.11 on 2026-02-08 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toponym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bash', models.CharField(max_length=200, verbose_name='Название на башкирском')),
                ('name_rus', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('type', models.CharField(choices=[('spring', 'Родник'), ('rock', 'Скала/Утёс'), ('mountain', 'Гора'), ('river', 'Река'), ('lake', 'Озеро'), ('forest', 'Лес/Роща'), ('field', 'Поле/Луг'), ('ravine', 'Овраг/Лог'), ('tract', 'Урочище'), ('other', 'Другое')], max_length=50, verbose_name='Тип объекта')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('description', models.TextField(blank=True, verbose_name='Описание/легенда')),
                ('location_note', models.TextField(blank=True, verbose_name='Примечание к местоположению')),
                ('municipality', models.CharField(blank=True, max_length=300, verbose_name='Муниципальный район/поселение')),
                ('photo', models.ImageField(blank=True, upload_to='toponyms/photos/', verbose_name='Фотография')),
                ('audio', models.FileField(blank=True, upload_to='toponyms/audio/', verbose_name='Аудиозапись')),
                ('reg_number', models.CharField(blank=True, max_length=50, verbose_name='Регистрационный номер (АГКГН)')),
                ('map_nomenclature', models.CharField(blank=True, max_length=50, verbose_name='Номенклатура карты')),
                ('external_links', models.JSONField(blank=True, default=dict, verbose_name='Внешние ссылки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано'), ('disputed', 'Спорный'), ('rejected', 'Отклонено')], default='moderation', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('votes_for', models.IntegerField(default=0, verbose_name='Голосов за')),
                ('votes_against', models.IntegerField(default=0, verbose_name='Голосов против')),
                ('disputed_alternatives', models.JSONField(blank=True, default=list, verbose_name='Альтернативные варианты названия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
            ],
            options={
                'verbose_name': 'Топоним',
                'verbose_name_plural': 'Топонимы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'type'], name='toponyms_to_status_236835_idx'), models.Index(fields=['latitude', 'longitude'], name='toponyms_to_latitud_ac7bff_idx')],
            },
        ),
    ]
