# Generated by Django 5.2.11 on 2026-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toponym',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Ссылка на объект в Google My Maps', verbose_name='Ссылка на Google Maps'),
        ),
    ]
